openapi: 3.2.0
info:
  title: Cilium Prefilter API
  description: Cilium
  version: v1beta1
servers:
- url: /v1
tags:
- name: Prefilter
paths:
  /prefilter:
    get:
      summary: Retrieve list of CIDRs
      tags:
      - Prefilter
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Prefilter'
        '500':
          description: Prefilter get failed
          x-go-name: Failure
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      operationId: getPrefilter
      x-operation-id-source: derived
    patch:
      summary: Update list of CIDRs
      tags:
      - Prefilter
      parameters:
      - $ref: '#/components/parameters/prefilter-spec'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Prefilter'
        '403':
          description: Forbidden
        '461':
          description: Invalid CIDR prefix
          x-go-name: InvalidCIDR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Prefilter update failed
          x-go-name: Failure
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      operationId: patchPrefilter
      x-operation-id-source: derived
    delete:
      summary: Delete list of CIDRs
      tags:
      - Prefilter
      parameters:
      - $ref: '#/components/parameters/prefilter-spec'
      responses:
        '200':
          description: Deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Prefilter'
        '403':
          description: Forbidden
        '461':
          description: Invalid CIDR prefix
          x-go-name: InvalidCIDR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Prefilter delete failed
          x-go-name: Failure
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      operationId: deletePrefilter
      x-operation-id-source: derived
components:
  schemas:
    PrefilterStatus:
      description: CIDR ranges implemented in the Prefilter
      type: object
      properties:
        realized:
          $ref: '#/components/schemas/PrefilterSpec'
    PrefilterSpec:
      description: CIDR ranges implemented in the Prefilter
      type: object
      properties:
        revision:
          type: integer
        deny:
          type: array
          items:
            type: string
    Prefilter:
      description: Collection of endpoints to be served
      type: object
      properties:
        spec:
          $ref: '#/components/schemas/PrefilterSpec'
        status:
          $ref: '#/components/schemas/PrefilterStatus'
    Error:
      type: string
  parameters:
    prefilter-spec:
      name: prefilter-spec
      description: List of CIDR ranges for filter table
      required: true
      in: body
      schema:
        $ref: '#/components/schemas/PrefilterSpec'
x-schemes:
- unix
